# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ayushms890@gmail.com
author_name: Ayush Singh
contract_name: hello_worl
deployment_language: python
preset_name: starter
project_name: algoconsent-contract

